sudo: false

language: java

cache:
  directories:
    - ~/.m2

addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet

jdk:
  - oraclejdk8

script:
  # - ./make-release.sh --command test --dirty-scm true
  - mvn -T 1C test
